### ISSUE TITLE
terraform-validator crashes when validating google_storage_bucket with google_storage_bucket_iam_member

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-validator#216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v2021-04-07

### Affected Resource(s)

* google_storage_bucket_iam_member
* google_storage_bucket

### Terraform Plan JSON

Gist for the json https://gist.github.com/daniel-cit/607b1251640b6f5f5b11a8b7d8657f9b

Created from this terraform file, which is the Google  Log Export Module example for [Storage+Folder](https://github.com/terraform-google-modules/terraform-google-log-export/tree/master/examples/storage/folder)

```terraform
variable "project_id" {
  description = "The ID of the project in which the log export will be created."
  type        = string
}

variable "parent_resource_id" {
  description = "The ID of the project in which storage bucket destination will be created."
  type        = string
}

resource "random_string" "suffix" {
  length  = 4
  upper   = false
  special = false
}

module "log_export" {
  source                 = "terraform-google-modules/log-export/google"
  destination_uri        = module.destination.destination_uri
  filter                 = "resource.type = gce_instance"
  log_sink_name          = "storage_folder_${random_string.suffix.result}"
  parent_resource_id     = var.parent_resource_id
  parent_resource_type   = "folder"
  unique_writer_identity = true
}

module "destination" {
  source                   = "terraform-google-modules/log-export/google//modules/storage"
  project_id               = var.project_id
  storage_bucket_name      = "storage_folder_${random_string.suffix.result}"
  log_sink_writer_identity = module.log_export.writer_identity
}
```

### Debug Output

https://gist.github.com/daniel-cit/e0f2e3642ac5d83a62d7aea2b2fd74d3

### Expected Behavior

terraform-validator should have validated the plan.

### Actual Behavior

terraform-validator crashes with error:

```
Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update fetching asset: Import id "" doesn't match any of the accepted formats: [b/(?P<bucket>[^/]+) (?P<bucket>[^/]+)]
```

### Steps to Reproduce

1. `terraform-validator validate bucket_iam.json --policy-path="a-valid-policy-library" --project="a-valid-project-id"`

### References

* #0000

**Comment by c2thorn** [comment]
Hi @daniel-cit, thanks for your patience. I was able to recreate the error using the module. This is happening because the `module.destination.google_storage_bucket.bucket` `name` is dependent on the [random provider string](https://github.com/terraform-google-modules/terraform-google-log-export/blob/baca38407d74a8c9d36db4840062083ad75ee222/examples/storage/folder/main.tf#L37) and not known at plan time. This leads to the bucket `name` is not [appearing as a value](https://gist.github.com/daniel-cit/607b1251640b6f5f5b11a8b7d8657f9b#file-bucket_iam-json-L92) for `module.destination.google_storage_bucket_iam_member.storage_sink_member`, which uses the name as an ID when fetching.

It seems the correct approach here would be for Validator to detect this scenario, apply a warning, and skip the resource. We've seen this for other resources and would like to build this as a general feature. This is a larger task so we will have to triage it as a such.

In the meantime, a less than desirable workaround may be to remove the random_string for the bucket name. This would allow Validator to have a fixed value for the bucket ID.

**Comment by c2thorn** [comment]
@morgante The problem here is in the IAM mapper fetch `FetchBucketIamPolicy`. We can't pass a random UUID since the fetch function will actually send a request for that resource.

@daniel-cit The plan is to modify `FetchBucketIamPolicy` upstream since that is where this fix will be when https://github.com/GoogleCloudPlatform/terraform-validator/issues/217 is complete. But yes if we can't read the bucket name we should return the empty result.
