### ISSUE TITLE
Feature req to enable rate limiting/shaping of API requests

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [GoogleCloudPlatform/terraform-validator#252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

Could we implement a rate limiting feature to shape Google resourceManager API requests to ensure we fit inside a given project's quota.

### New or Affected Resource(s)

N/A?

### Terraform-google-conversion support?

N/A?

### References

N/A wasn't able to find any references around this. I'm not even sure which component is making the API request yet!

**Comment by melinath** [comment]
Every changed terraform resource triggers a call to augmentAsset, which calls an ancestry manager's GetAncestryWithResource method, which calls the resourceManager API. However, the ancestry manager caches the project  ancestry, so it should be getting called at most once per run per project. Since this is a per-project quota, we wouldn't expect to see any issues.

Could you elaborate a bit?

- What is the quota you're having trouble fitting inside?
- How many terraform resources you're validating, roughly? (10, 100, 1000, 10000)
- Can you share any particular minimal terraform config that triggers the issue?
- Is there anything unusual about your terraform config?

**Comment by Jake-Mok-Nelson** [comment]
I think we were actually already hitting our rate limit outside of this and this tool was how it became visible at the time. I don't believe this is problem with Codefresh so I'm closing the issue. Thanks for your support.
